name: "Test"
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: ["24.x"]
        elixir: ["1.16.3"]
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        name: Setup elixir
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: |
          mix deps.get
          mix compile --warnings-as-errors
          mix format --check-formatted
          mix test
